#!/usr/bin/env node
// sync-docs.mjs — copy + transform Evidence doc pages into the skill's reference/ folder.
//
// Why this exists: sites/docs/pages is synced from an upstream repo and must not be
// edited. This script produces an LLM-friendly COPY so the skill stays self-contained
// and portable to standalone Evidence projects. Re-run it after every upstream sync;
// `git diff reference/` then shows exactly what changed.
//
// Transform applied (conservative — favors not mangling over completeness):
//   1. Drop `<div slot='preview'>…</div>` blocks inside <DocTab>. These are live
//      component renders that (a) an LLM cannot see and (b) exactly duplicate the
//      adjacent ```markdown code fence. ~291 of them across the docs.
//   2. Drop the `<DocTab …>` / `</DocTab>` wrapper lines, leaving the code fence.
//   3. Strip site-only frontmatter keys (sidebar_position, sidebar_link, og, …),
//      keeping title/description/queries.
//   4. Convert each component's `<PropListing>` props into one markdown table
//      (Prop | Description | Options | Default). Descriptions live either in an
//      attribute or as tag body text, and values can embed `>`, `{[…]}` arrays, and
//      `backtick` literals, so parsing uses a quote/brace-aware scanner (see below).
//   5. Prepend a provenance banner so nobody hand-edits the generated files.
//
// Usage:
//   node sync-docs.mjs                 # uses default paths (run from anywhere in repo)
//   node sync-docs.mjs <srcDir> <dstDir>
//   EVIDENCE_DOCS_SRC=/path node sync-docs.mjs

import { readdir, readFile, writeFile, mkdir, rm, stat } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join, dirname, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const skillRoot = resolve(__dirname, '..');

// Default source: the docs pages in this monorepo. Walk up to find it so the script
// works whether invoked from the skill folder or the repo root.
function findDefaultSrc() {
	if (process.env.EVIDENCE_DOCS_SRC) return resolve(process.env.EVIDENCE_DOCS_SRC);
	let dir = skillRoot;
	for (let i = 0; i < 8; i++) {
		const candidate = join(dir, 'sites', 'docs', 'pages');
		if (existsSync(candidate)) return candidate;
		dir = dirname(dir);
	}
	return null;
}

const srcDir = process.argv[2] ? resolve(process.argv[2]) : findDefaultSrc();
const dstDir = process.argv[3] ? resolve(process.argv[3]) : join(skillRoot, 'reference');

if (!srcDir || !existsSync(srcDir)) {
	console.error(
		'Could not locate the Evidence docs source (sites/docs/pages).\n' +
			'Run this from inside the evidence monorepo, or pass the path:\n' +
			'  node sync-docs.mjs /path/to/sites/docs/pages'
	);
	process.exit(1);
}

const BANNER =
	'<!-- GENERATED by scripts/sync-docs.mjs from sites/docs/pages. DO NOT EDIT. Re-run the script after syncing upstream docs. -->\n\n';

// Frontmatter keys worth keeping for skill consumers. Everything else is site chrome.
const KEEP_FRONTMATTER = new Set(['title', 'description', 'queries']);

/** Strip site-only frontmatter, keeping only useful keys. */
function transformFrontmatter(text) {
	if (!text.startsWith('---\n')) return text;
	const end = text.indexOf('\n---', 4);
	if (end === -1) return text;
	const fmBlock = text.slice(4, end);
	const rest = text.slice(end + 4).replace(/^\n/, '');

	const kept = [];
	let currentKeyKept = false;
	for (const line of fmBlock.split('\n')) {
		const keyMatch = /^([A-Za-z0-9_-]+):/.exec(line);
		if (keyMatch) {
			currentKeyKept = KEEP_FRONTMATTER.has(keyMatch[1]);
			if (currentKeyKept) kept.push(line);
		} else if (currentKeyKept && (/^\s+/.test(line) || /^-\s/.test(line))) {
			// continuation of the current key: an indented line, or a flush-left
			// YAML block-sequence item (`- foo.sql`) under e.g. `queries:`.
			kept.push(line);
		}
	}
	if (kept.length === 0) return rest;
	return `---\n${kept.join('\n')}\n---\n\n${rest}`;
}

/**
 * Remove `<div slot='preview'>…</div>` blocks and <DocTab> wrappers via a line-based
 * scanner with div-depth tracking (robust to nested divs; regex is not).
 */
function transformDocTabs(text) {
	const lines = text.split('\n');
	const out = [];
	let previewDepth = 0; // >0 means we're inside a slot='preview' div, skipping lines

	for (const line of lines) {
		if (previewDepth > 0) {
			previewDepth += countOpens(line) - countCloses(line);
			continue; // skip everything inside the preview render
		}

		// Enter a preview block: a <div ... slot='preview' ...> (single or double quotes)
		if (/<div[^>]*slot=['"]preview['"]/.test(line)) {
			previewDepth = countOpens(line) - countCloses(line);
			// If the div opens and closes on one line, previewDepth is 0 and we've dropped it.
			continue;
		}

		// Drop DocTab wrapper lines entirely (keep their inner code fences).
		const trimmed = line.trim();
		if (/^<DocTab\b[^>]*>$/.test(trimmed) || trimmed === '</DocTab>') continue;

		out.push(line);
	}

	return collapseBlankRuns(out.join('\n'));
}

function countOpens(line) {
	return (line.match(/<div\b/g) || []).length;
}
function countCloses(line) {
	return (line.match(/<\/div>/g) || []).length;
}

/** Collapse 3+ consecutive blank lines (left by removed blocks) into a single blank line. */
function collapseBlankRuns(text) {
	return text.replace(/\n{3,}/g, '\n\n');
}

// ---------------------------------------------------------------------------
// PropListing -> markdown table
//
// Docs declare each component prop as a <PropListing …/> block, in two shapes:
//   self-closing:  <PropListing name=x options=… description="…" />
//   block form:    <PropListing name=x …>\n\n<description text>\n\n</PropListing>
// Attribute values can contain `>` (e.g. an <a href=…> inside a description),
// balanced {[ … ]} arrays, and `backtick` template literals — so the boundary
// must be found with a quote/brace-aware scanner, not a regex. Consecutive
// blocks are merged into one table so a component's prop API reads as a unit.
// ---------------------------------------------------------------------------

const PROP_TAG = '<PropListing';

/** Skip a quoted string starting at s[pos] (a quote char). Returns index past the close. */
function skipQuoted(s, pos) {
	const quote = s[pos];
	for (let i = pos + 1; i < s.length; i++) {
		if (s[i] === '\\') { i++; continue; } // escaped char
		if (s[i] === quote) return i + 1;
	}
	return s.length;
}

/** Skip a `{ … }` group at s[pos] (an opening brace), honoring nested quotes/backticks/braces. */
function skipBraces(s, pos) {
	let depth = 0;
	for (let i = pos; i < s.length; i++) {
		const c = s[i];
		if (c === '"' || c === "'" || c === '`') { i = skipQuoted(s, i) - 1; continue; }
		if (c === '{') depth++;
		else if (c === '}' && --depth === 0) return i + 1;
	}
	return s.length;
}

/**
 * Parse one PropListing starting at `start` (where s[start] begins the tag).
 * Returns { props: [...], end } or null if it isn't a well-formed tag. `props` is
 * usually a single prop, but a block-form body can nest sibling PropListings
 * (an upstream authoring quirk); those are hoisted out as their own props and the
 * leftover body text becomes the parent's description.
 */
function parsePropListing(s, start) {
	let i = start + PROP_TAG.length;
	// The char after the tag name must be whitespace or the tag close.
	if (!/[\s/>]/.test(s[i] ?? '')) return null;

	const attrsStart = i;
	let selfClosing = false;
	let tagEnd = -1;
	for (; i < s.length; i++) {
		const c = s[i];
		if (c === '"' || c === "'" || c === '`') { i = skipQuoted(s, i) - 1; continue; }
		if (c === '{') { i = skipBraces(s, i) - 1; continue; }
		if (c === '/' && s[i + 1] === '>') { selfClosing = true; tagEnd = i + 2; break; }
		if (c === '>') { tagEnd = i + 1; break; }
	}
	if (tagEnd === -1) return null;

	const attrs = parseAttrs(s.slice(attrsStart, tagEnd - (selfClosing ? 2 : 1)));

	if (selfClosing) {
		return { props: [{ attrs, description: attrs.description ?? '' }], end: tagEnd };
	}

	const close = s.indexOf('</PropListing>', tagEnd);
	if (close === -1) return null;
	const { props: nested, text } = extractProps(s.slice(tagEnd, close));
	const description = text.trim() || attrs.description || '';
	const end = close + '</PropListing>'.length;
	return { props: [...nested, { attrs, description }], end };
}

/** Pull every PropListing out of a string, returning the parsed props and the text minus tags. */
function extractProps(str) {
	const props = [];
	let text = '';
	let i = 0;
	while (i < str.length) {
		const j = str.indexOf(PROP_TAG, i);
		if (j === -1) { text += str.slice(i); break; }
		text += str.slice(i, j);
		const parsed = parsePropListing(str, j);
		if (!parsed) { text += PROP_TAG; i = j + PROP_TAG.length; continue; }
		props.push(...parsed.props);
		i = parsed.end;
	}
	return { props, text };
}

/** Parse an attribute string into a { key: value } map. Bare flags map to "true". */
function parseAttrs(str) {
	const attrs = {};
	let i = 0;
	while (i < str.length) {
		while (i < str.length && /\s/.test(str[i])) i++;
		const keyMatch = /^[A-Za-z0-9_-]+/.exec(str.slice(i));
		if (!keyMatch) break;
		const key = keyMatch[0];
		i += key.length;
		while (i < str.length && /\s/.test(str[i])) i++;
		if (str[i] !== '=') {
			attrs[key] = 'true'; // bare flag, e.g. `required`
			continue;
		}
		i++; // skip '='
		while (i < str.length && /\s/.test(str[i])) i++;
		const c = str[i];
		if (c === '"' || c === "'") {
			const endQ = skipQuoted(str, i);
			attrs[key] = str.slice(i + 1, endQ - 1);
			i = endQ;
		} else if (c === '{') {
			const endB = skipBraces(str, i);
			attrs[key] = formatBraceValue(str.slice(i + 1, endB - 1));
			i = endB;
		} else {
			const bare = /^\S+/.exec(str.slice(i));
			attrs[key] = bare ? bare[0] : '';
			i += bare ? bare[0].length : 0;
		}
	}
	return attrs;
}

/** Turn a `{ … }` attribute inner value into readable text (arrays → comma list). */
function formatBraceValue(inner) {
	const t = inner.trim();
	const arr = /^\[(.*)\]$/s.exec(t);
	if (arr) {
		return arr[1]
			.split(',')
			.map((x) => x.trim().replace(/^['"`]|['"`]$/g, ''))
			.filter(Boolean)
			.join(', ');
	}
	return t.replace(/^['"`]|['"`]$/g, '');
}

/** Make a value safe for a one-line markdown table cell. */
function cell(v) {
	return (v ?? '').replace(/\s+/g, ' ').replace(/\|/g, '\\|').trim();
}

// --- Enum-gap augmentation ---------------------------------------------------
// Upstream sometimes documents an incomplete `options` enum for a prop while its
// own code examples use more values (seen for `contentType`, `labelPosition`). We
// detect those example-only values and append them to the Options cell, marked, so
// Claude sees every valid value. Self-healing: recomputed from the docs each sync.

// Options cells that name a value TYPE, not a literal enum — skip these.
const FREEFORM = /column name|array|query name|string|number|boolean|expression|see |http|\{/i;
const TYPE_PLACEHOLDER =
	/^(url|text|col|column|color|colour|date|datetime|json|css|html|path|value|name|id|px|em|rem|percent|hex)$/i;

/** If an Options cell is a literal enum, return its lowercased value set; else null. */
function optionEnum(optionsCell) {
	const c = (optionsCell ?? '').trim();
	if (!c || FREEFORM.test(c)) return null;
	const tokens = c.split(',').map((t) => t.trim());
	if (tokens.length === 1 && TYPE_PLACEHOLDER.test(tokens[0])) return null;
	if (!tokens.every((t) => /^[A-Za-z0-9_%-]+$/.test(t))) return null;
	return new Set(tokens.map((t) => t.toLowerCase()));
}

/** Map prop name -> Set of clean literal values used with it in the file's code fences. */
function exampleUsages(text, propNames) {
	const used = new Map();
	if (propNames.size === 0) return used;
	const alt = [...propNames].join('|');
	const re = new RegExp(`\\b(${alt})=(?:"([^"{}]+)"|'([^'{}]+)'|([A-Za-z0-9_%.-]+))`, 'g');
	for (const block of text.match(/```[\s\S]*?```/g) || []) {
		let m;
		while ((m = re.exec(block))) {
			const val = (m[2] || m[3] || m[4] || '').toLowerCase();
			// Only clean enum-like literals; reject example data (urls, paths, col refs).
			if (!/^[a-z][a-z0-9]*[0-9]?$/.test(val)) continue;
			if (!used.has(m[1])) used.set(m[1], new Set());
			used.get(m[1]).add(val);
		}
	}
	return used;
}

/** Render a run of parsed props as one markdown table, augmenting incomplete enums. */
function propsTable(props, usages = new Map(), nameCounts = new Map()) {
	const rows = props.map((p) => {
		const name = `\`${cell(p.attrs.name ?? '')}\`` + (p.attrs.required === 'true' ? ' _(required)_' : '');
		let options = cell(p.attrs.options);
		const documented = optionEnum(p.attrs.options);
		// Only augment when the prop is defined once in the file — otherwise the same
		// name may belong to several components (e.g. labelPosition on ReferenceLine vs
		// ReferenceArea) and file-global example values can't be attributed correctly.
		if (documented && nameCounts.get(p.attrs.name) === 1) {
			const extra = [...(usages.get(p.attrs.name) ?? [])].filter((v) => !documented.has(v));
			if (extra.length) options += ` _(+examples: ${extra.join(', ')})_`;
		}
		return `| ${name} | ${cell(p.description)} | ${options} | ${cell(p.attrs.defaultValue)} |`;
	});
	return ['| Prop | Description | Options | Default |', '|------|-------------|---------|---------|', ...rows].join(
		'\n'
	);
}

function transformPropListings(text) {
	// Pre-scan: every prop name in the file, how many times each is defined, and the
	// enum values its examples use. nameCounts gates augmentation to unambiguous props.
	const allNames = extractProps(text).props.map((p) => p.attrs.name).filter(Boolean);
	const propNames = new Set(allNames);
	const nameCounts = new Map();
	for (const n of allNames) nameCounts.set(n, (nameCounts.get(n) ?? 0) + 1);
	const usages = exampleUsages(text, propNames);

	let out = '';
	let i = 0;
	while (i < text.length) {
		const j = text.indexOf(PROP_TAG, i);
		if (j === -1) {
			out += text.slice(i);
			break;
		}
		out += text.slice(i, j);

		// Accumulate a run of consecutive PropListings (only whitespace between them).
		const run = [];
		let cursor = j;
		while (true) {
			const parsed = parsePropListing(text, cursor);
			if (!parsed) break;
			run.push(...parsed.props);
			let k = parsed.end;
			while (k < text.length && /\s/.test(text[k])) k++;
			if (text.startsWith(PROP_TAG, k)) {
				cursor = k;
			} else {
				cursor = parsed.end;
				break;
			}
		}

		if (run.length === 0) {
			// Not actually a valid tag (e.g. the string appears in prose); emit literally.
			out += PROP_TAG;
			i = j + PROP_TAG.length;
			continue;
		}
		out += '\n' + propsTable(run, usages, nameCounts) + '\n';
		i = cursor;
	}
	return out;
}

function transform(text) {
	let t = transformFrontmatter(text);
	t = transformDocTabs(t);
	t = transformPropListings(t);
	t = collapseBlankRuns(t);
	return BANNER + t.trimStart();
}

async function walk(dir) {
	const entries = await readdir(dir, { withFileTypes: true });
	const files = [];
	for (const e of entries) {
		const full = join(dir, e.name);
		if (e.isDirectory()) {
			files.push(...(await walk(full)));
		} else if (e.isFile() && /\.md$/.test(e.name)) {
			files.push(full);
		}
	}
	return files;
}

async function main() {
	console.log(`Source: ${srcDir}`);
	console.log(`Dest:   ${dstDir}`);

	// Clean dest so deleted upstream pages don't linger.
	if (existsSync(dstDir)) await rm(dstDir, { recursive: true, force: true });
	await mkdir(dstDir, { recursive: true });

	const files = await walk(srcDir);
	let count = 0;
	let srcBytes = 0;
	let dstBytes = 0;

	for (const file of files) {
		const rel = relative(srcDir, file);
		const raw = await readFile(file, 'utf8');
		const transformed = transform(raw);
		const outPath = join(dstDir, rel);
		await mkdir(dirname(outPath), { recursive: true });
		await writeFile(outPath, transformed, 'utf8');
		srcBytes += Buffer.byteLength(raw);
		dstBytes += Buffer.byteLength(transformed);
		count++;
	}

	const pct = srcBytes ? Math.round((1 - dstBytes / srcBytes) * 100) : 0;
	console.log(`Transformed ${count} files.`);
	console.log(
		`Size: ${(srcBytes / 1024).toFixed(0)}K → ${(dstBytes / 1024).toFixed(0)}K (${pct}% smaller)`
	);
}

main().catch((err) => {
	console.error(err);
	process.exit(1);
});
